#8 create: sidebar + header
lamxuanthinh/DGU pull request #35
Opened 2023-05-27 11:05 UTC by ImmChad

2023-05-27 11:41 UTC, lamxuanthinh requested changes

2023-05-27 11:41 UTC, lamxuanthinh commented on components/layout/Header/index.tsx
> +        {/* <SectionProfile>
you should clear the code command

2023-05-27 11:41 UTC, lamxuanthinh commented on Views/Profile/index.tsx
> +                            <i className="fa-solid fa-pen icon-edit-profile"></i>
You can handle the style `icon `in the file  `ProfileStyled.ts` ...

2023-05-27 11:41 UTC, lamxuanthinh commented on components/layout/Header/headerStyled.ts
> +
Please code clean

2023-05-27 11:41 UTC, lamxuanthinh commented on pages/index.tsx
> -import type { NextPage } from "next";
You should use ` { NextPage }`

2023-05-27 23:42 UTC, ImmChad commented on components/layout/Header/index.tsx
> +        {/* <SectionProfile>
This is the code prepare after login, I don't know how to handle if I deletes it, and after that how to use it again when I want

2023-05-27 23:45 UTC, ImmChad commented on Views/Profile/index.tsx
> +                            <i className="fa-solid fa-pen icon-edit-profile"></i>
this is the code from LMD

2023-05-28 00:37 UTC, lamxuanthinh commented
Good

2023-05-28 00:37 UTC, merged